# Generated by Django 6.0.6 on 2026-06-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='cards.card', verbose_name='cartão'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='parcelas'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_add_to_bill',
            field=models.BooleanField(default=False, verbose_name='adicionar na fatura'),
        ),
    ]
