# Generated by Django 6.0.4 on 2026-05-20 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='saldo')),
                ('institution', models.CharField(blank=True, max_length=100, null=True, verbose_name='instituição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta bancária',
                'verbose_name_plural': 'contas bancárias',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_bank_account_per_user')],
            },
        ),
    ]
