# Generated by Django 6.0.5 on 2026-05-20 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('CHECKING', 'Conta Corrente'), ('SAVINGS', 'Conta Poupança'), ('INVESTMENT', 'Investimento')], default='CHECKING', max_length=20, verbose_name='tipo da conta'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='closing_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia de fechamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='payment_due_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia de vencimento (pagamento)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='institution',
            field=models.CharField(blank=True, choices=[('BB', 'Banco do Brasil'), ('CAIXA', 'Caixa Econômica Federal'), ('BRADESCO', 'Bradesco'), ('ITAU', 'Itaú'), ('SANTANDER', 'Santander'), ('NUBANK', 'Nubank'), ('INTER', 'Inter'), ('BTG', 'BTG Pactual'), ('C6', 'C6 Bank'), ('OUTRO', 'Outro')], max_length=20, null=True, verbose_name='banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='descrição'),
        ),
    ]
