# Generated by Django 6.0.6 on 2026-06-30 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_accounts', '0002_bankaccount_account_type_bankaccount_closing_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, verbose_name='descrição')),
                ('last_numbers', models.CharField(max_length=4, verbose_name='últimos números')),
                ('limit', models.IntegerField(default=0, verbose_name='limite')),
                ('type', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=10, verbose_name='tipo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='bank_accounts.bankaccount', verbose_name='conta bancária')),
            ],
            options={
                'verbose_name': 'cartão',
                'verbose_name_plural': 'cartões',
            },
        ),
    ]
