# Generated by Django 6.0.6 on 2026-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito'), ('BOTH', 'Ambos')], max_length=10, verbose_name='tipo'),
        ),
    ]
